name: Deploy multi-container Fibonacci calculator
"on":
  push:
    branches:
      - main
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t henrychung/test-react -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true henrychung/test-react npm test
  build_images:
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t henrychung/complex-client ./client
      - run: docker build -t henrychung/complex-nginx ./nginx
      - run: docker build -t henrychung/complex-server ./server
      - run: docker build -t henrychung/complex-worker ./worker
